### ISSUE TITLE
节点ping正常, curl Google return Empty reply from server

### ISSUE THREAD

**Issue by aibot88** [TyrantLucifer/ssr-command-client#13]
我完成订阅操作后, 多次尝试create fast-node和自定义的node, 使用提供的ALL_PROXY命令进行socks5的设置; 期间没有任何报错信息;但是最终curl Google的时候报E52 Emply reply from server错误.wget Google显示被墙； 经检测我的节点在window表现正常？请问这边如何定位问题？

![empty-reply-from-server](https://user-images.githubusercontent.com/32379225/89282611-5ea02b80-d67e-11ea-8bd9-89c76602295d.jpg)

**Comment by TyrantLucifer** [comment]
出现这种情况，是节点不可用，你确认你生成的节点json文件和你windows用的节点一致，可以先使用python main.py -l 查看节点id编号，然后使用python main.py -c id去生成文件，python main.py -s启动即可。wget测试需要指定dns服务器，推荐使用我readme中的方式进行测试节点是否正常。
