### ISSUE TITLE
sudo情况下HOME路径错误

### ISSUE THREAD

**Issue by DualThrust** [TyrantLucifer/ssr-command-client#15]
debian 9.13
执行sudo python3 main.py -l
会把执行结果写到/root/.ssr-command-client下面去

**Comment by TyrantLucifer** [comment]
切换到develop分支吧，那个版本不再会有sudo的问题

**Comment by TyrantLucifer** [comment]
如果不想切换的话，修改/etc/sudoers 文件，将`Defaults env_reset`修改为`Defaults !env_reset`

**Comment by DualThrust** [comment]
已经切到develop
发现几个问题
1. 需要pip3一下qrcode 没有加到requirement.txt里面
2. fping在debian9上面没有4的参数 改成-Dae才行
3. 需要删一下~/.ssr-command-client的缓存 貌似是因为之前用ping3的时候文件权限是root
4. 那个main.sh 如果可以的话建议加个cd到脚本所在目录 不然没法从其他目录调用这个脚本

**Comment by TyrantLucifer** [comment]
已调整requirement，fping的事情，我再查验一下相关文档吧，从官网上来看，只要装了fping都会有-4的这个option，main.sh是跟着项目走的，所以只能在项目目录下用，定位并不是在外部封装的一个可执行程序。

**Comment by DualThrust** [comment]
关于fping 应该是版本的问题
debian9上是3.5 没有-4这个只测ipv4的选项 
ubuntu18.04上是4.0 已经支持这个选项了
我自己fork了一份 调整一下就好 代码还是比较清晰易懂的 我这种没怎么学过python的都看得懂
