### ISSUE TITLE
正确订阅了url，但解析出错

### ISSUE THREAD

**Issue by XinyuLyu** [TyrantLucifer/ssr-command-client#18]
![image](https://user-images.githubusercontent.com/33551398/92703127-8886f500-f384-11ea-8778-8c36d338c9a9.png)

![image](https://user-images.githubusercontent.com/33551398/92703004-6beabd00-f384-11ea-88bf-f0fb5e7f15a4.png)

**Comment by TyrantLucifer** [comment]
检查订阅链接是否可用。

**Comment by XinyuLyu** [comment]
可以用的

**Comment by XinyuLyu** [comment]
添加订阅url之后，查看已经添加的url和刚添加的url不一致
![微信截图_20200911094608](https://user-images.githubusercontent.com/33551398/92840472-b23b2d00-f413-11ea-9bba-3eff62da2978.png)
![微信截图_20200911094626](https://user-images.githubusercontent.com/33551398/92840463-b0716980-f413-11ea-833f-82e3cc3cbea0.png)
token那一段添加之后就没有了，应该是这个原因导致的，但是不知道如何解决。

**Comment by TyrantLucifer** [comment]
用双引号把你的链接括起来，因为你的链接里有&符号
