### ISSUE TITLE
question: switch from Shadowsocksx-ng-r8

### ISSUE THREAD

**Issue by ssh352** [TyrantLucifer/ssr-command-client#19]
I currently use https://github.com/qinyuhang/ShadowsocksX-NG-R/releases/download/1.4.4-r8/ShadowsocksX-NG-R8.dmg on macOS. Are functionalities the same between the two? Thank you.

**Comment by TyrantLucifer** [comment]
ssr-command-client是在Unix环境下使用的ssr客户端，不适用于图形化界面操作系统使用，你使用的工具是 mac os下的一款ssr客户端。
