### ISSUE TITLE
ping过程改成并发吧

### ISSUE THREAD

**Issue by neosun100** [TyrantLucifer/ssr-command-client#2]
这个问题比较急迫，ssr比较多的情况下，逐个ping异常缓慢

选取最快的id，我写了个shell，你可以参考下

python3 main.py -l | grep -v  ∞| grep -v +  | sort -g -k 6 |  tr -d \|  | awk '{print $1}'  |head -n 2 | tail -n 1

**Comment by TyrantLucifer** [comment]
> 这个问题比较急迫，ssr比较多的情况下，逐个ping异常缓慢
> 
> 选取最快的id，我写了个shell，你可以参考下
> 
> python3 main.py -l | grep -v ∞| grep -v + | sort -g -k 6 | tr -d | | awk '{print $1}' |head -n 2 | tail -n 1

我已经更新了新的版本，现在ping过程已经加快了，你尝试pull一下，如果还是慢的话，我可以搞成并发，目前寻找最快节点的功能正在开发中，平时上班较忙，请稍等~~

**Comment by TyrantLucifer** [comment]
新版功能已经完成，使用--fast-node可以自动生成配置json，如果联合-p选线可以指定本地代理端口，请享用，如果还有其他问题请回复我，谢谢~
