### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by xspkwy** [TyrantLucifer/ssr-command-client#21]
博主你好，按照你的设置更新了我自己订阅的ssr链接，并且按照后面的步骤配置好服务器了，有这么几个问题：
1. "config json file is update~~ " 这句之后是否默认设置当前节点作为代理节点了？以及这个config文件存在哪里？
2. setproxy设置好代理后，ip命令会提示“curl: (52) Empty reply from server”，并且用git、curl等命令也实际没有挂到代理，这是什么问题？

**Comment by TyrantLucifer** [comment]
1. 你理解的第一条是对的，当你执行`python main.py -c xx`会在`~/.ssr_command_client`下生成`config.json`

2. 出现`curl: (52) Empty reply from server`可能会有两个原因：

- 代理未启动
使用`lsof -i :1080`查看当前端口是否存在进程

- 节点失效，请确认节点是否在其他设备可用

3. 请问你用的是那个分支，`develop`还是`master`？

**Comment by xspkwy** [comment]
我目前用的是默认的master分支。
- lsof命令查看之后，设置代理前没有其他进程占用；设置代理后有两个进程占用：
`COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME`
`python  25048 root    4u  IPv4 50403286      0t0  TCP localhost:socks (LISTEN)`
`python  25048 root    6u  IPv4 50403287      0t0  UDP localhost:socks`

- 节点在我本地系统试过了，google、youtube什么的都没问题

**Comment by xspkwy** [comment]
> 我目前用的是默认的master分支。
> 
> * lsof命令查看之后，设置代理前没有其他进程占用；设置代理后有两个进程占用：
>   `COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME`
>   `python  25048 root    4u  IPv4 50403286      0t0  TCP localhost:socks (LISTEN)`
>   `python  25048 root    6u  IPv4 50403287      0t0  UDP localhost:socks`
> * 节点在我本地系统试过了，google、youtube什么的都没问题

不好意思，我重来了一遍，这回没问题了。有点奇怪，可能是之前挂的节点不稳定。

**Comment by TyrantLucifer** [comment]
好的，如果有问题了可以随时提出issue，希望它能带给你好的体验，如果觉得好用的话可以来个star哟～～
