### ISSUE TITLE
树莓派armbian环境运行成功代理失败

### ISSUE THREAD

**Issue by JiehangXie** [TyrantLucifer/ssr-command-client#29]
`2021-02-06 05:35:56,497 - Functions.py[line:76] - [startFastNode] - INFO: select fast node id - 11 name - [CT/CM]香港 03 delay - 43.049ms`
`2021-02-06 05:35:56,529 - daemon.py[line:123] - [daemon_start] - INFO: ShadowsocksR is started`
`root@aml:~/ssr-command-client# export ALL_PROXY=socks5://127.0.0.1:1080
root@aml:~/ssr-command-client# curl http://ip-api.com/json/?lang=zh-CN
curl: (7) Unable to receive initial SOCKS5 response.`

该节点在Windows和手机上都可以连接的，应该是正常的。树莓派上显示ssr进程也启动了，但是代理就失败了

**Comment by TyrantLucifer** [comment]
使用`lsof -i :1080`查看对应端口有没有进程，如果有的话，切换一个节点试试

**Comment by JiehangXie** [comment]
> 使用`lsof -i :1080`查看对应端口有没有进程，如果有的话，切换一个节点试试

`python3 26827 root    6u  IPv4 256036      0t0  TCP localhost:socks (LISTEN)
python3 26827 root    7u  IPv4 256037      0t0  UDP localhost:socks`

用进程的，而且也换了很多节点了，都不行

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/107113704-9d1bda80-689b-11eb-9b2c-c1da16086dcf.png)
经过本地测试，树莓派3B+，烧录的是官方镜像，测试没有问题，应该就是树莓派镜像的问题，定制版的镜像在网络上也有一些设置，这个需要去咨询一下对应提供镜像的服务商。
