### ISSUE TITLE
异常停止后无法重新启动SSR

### ISSUE THREAD

**Issue by withsalt** [TyrantLucifer/ssr-command-client#3]
描述：
我在通过main.py启动后，忘了关掉了就重启系统了。重启后重新开启ssr提示服务已经启动，关闭时又提示服务已经关闭。
![8NWy1H.jpg](https://s1.ax1x.com/2020/03/17/8NWy1H.jpg)

环境：
Ubuntu 18.04

**Comment by TyrantLucifer** [comment]
我已经修复了这个bug，请在项目文件夹执行git pull进行更新，重新执行python3 main.py -S停止服务，然后通过python3 main.py -s启动即可，感谢使用ssr-command-client，如果觉得好用的话欢迎跟朋友安利，让我们愉快的睁眼看世界和谷歌冲浪吧~~~

**Comment by withsalt** [comment]
感谢~~
