### ISSUE TITLE
请求增加一个setup.py便于安装启动

### ISSUE THREAD

**Issue by iamryanchia** [TyrantLucifer/ssr-command-client#31]
不知能否增加一个setup.py，像[shadowsocks](https://github.com/shadowsocks/shadowsocks/tree/master)一样，通过pip进行安装，通过ssrlocal启动。感谢！

**Comment by TyrantLucifer** [comment]
肝完了，重构了一遍代码，已经上传pypi，现在可以使用`pip install shadowsocksr-cli`进行愉快冲浪了~~
