### ISSUE TITLE
ERROR: create encryptor fail at port 1080 的解决方案

### ISSUE THREAD

**Issue by JabinGP** [TyrantLucifer/ssr-command-client#32]
### 问题描述

发现手上有很多的服务器无法成功连接使用，在查看 `~/.ssr-command-client/shadowsocksr.log` 及 `tcprelay.py` 进行 debug 后得到如下有效错误信息：

```log
{'method': 'chacha20-ietf'............} libsodium not found
```

原因一目了然，因为系统没有自带 chacha20 加密库。

### 解决方案

手动安装 chacha20 加密库，以 ubuntu18.04 为例：

```bash
sudo apt-get install -y libsodium-dev
```

也可以参考通过源码手动编译，[参考官网](https://doc.libsodium.org/installation)。

### 建议

似乎 ubuntu16 以上都不自带 libsodium ，其他发行版情况尚未考证，因为该问题无明显报错，较难察觉，如果作者认为有必要，我可以将以上信息添加到 README 以提醒使用者。

**Comment by TyrantLucifer** [comment]
哈哈哈，我以为玩linux大佬们都会注意到这个点的，这的确是个小坑，使用chacha20加密方式需要安装加密库，那我晚上回去更新一下，感谢，代码现在重构了，现在可以直接用pip安装了。🤪

**Comment by JabinGP** [comment]
我的😫

**Comment by baicaiaichibaicai** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10


安装完，依然报错
2022-05-23 02:39:19,984 - tcprelay.py[line:272] - [_create_encryptor] - ERROR: create encryptor fail at port 1080

**Comment by zezhishao** [comment]
> Distributor ID: Ubuntu Description: Ubuntu 21.10 Release: 21.10
> 
> 安装完，依然报错 2022-05-23 02:39:19,984 - tcprelay.py[line:272] - [_create_encryptor] - ERROR: create encryptor fail at port 1080

请问你解决了吗？
