### ISSUE TITLE
ssr怎么使用http呢,aiohttp只支持http不支持socks5

### ISSUE THREAD

**Issue by anlen123** [TyrantLucifer/ssr-command-client#34]
ssr怎么使用http呢,aiohttp只支持http不支持socks5

**Comment by TyrantLucifer** [comment]
你是指将socks5代理转成http代理吗？还是其他的，我不太明白你的需求，aiohttp你的意思是要用这个python包使用ssr开启的代理吗？

**Comment by JabinGP** [comment]
你似乎是想在 aiohttp 中使用代理，而 aiohttp 只支持 http 与 https 协议，基于这种需求你需要将 socks5 转为 http 。

如果需要将 socks5 转为 http ，我个人使用 privoxy ，你可以参考如下配置：

在 privoxy 配置文件（在我的电脑上是 /etc/privoxy/config ）中加入一行（本项目 socks5 默认工作在 1080 端口，如果有自定义端口则自行修改 1080 为其他）

```
forward-socks5 / 127.0.0.1:1080 .
```

重启 privoxy 后即可通过 privoxy 默认的 8118 端口（http://127.0.0.1:8118）使用 http 代理。

**Comment by anlen123** [comment]
好,谢谢你.我去试试
