### ISSUE TITLE
能够正常检测连接状态，但启动的 SOCKS5 服务不能正常访问

### ISSUE THREAD

**Issue by Herbert8** [TyrantLucifer/ssr-command-client#38]
可以正常更新订阅，测速连接都没问题，但是启动服务后，使用 cURL 访问报错：

```bash
$ curl -x 'socks5h://127.0.0.1:1080' google.com
```
报错信息：
```
curl: (7) Unable to receive initial SOCKS5 response.
```
使用其它工具测试相同的节点是可以访问的，所以应该不是节点问题。

测试环境：
CentOS 7.6，Python 3.9.2

安装方式：pip

**Comment by TyrantLucifer** [comment]
1. 检查1080端口是否有进程
2. 检查ip是否发生变化
3. 查看节点加密方式是否为chacha20，如果是的话请自行安装加密库
