### ISSUE TITLE
运行测试的例子代码会报错

### ISSUE THREAD

**Issue by ligenxun** [TyrantLucifer/ssr-command-client#39]
你好，运行测试是否连接的时候，是可以运行的，但是运行测速的时候，就会报错。
运行代码：
  `from shadowsocksr_cli.parse_utils import *
  from shadowsocksr_cli.network_test_utils import *
  ssr_url = "ssr://【ssr链接】"
  
  ssr_dict = ParseShadowsocksr.parse_shadowsocksr(ssr_url)
  ssr_dict = ShadowsocksrTest.test_shadowsocksr_connect(ssr_dict)
  ShadowsocksrTest.test_shadowsocksr_speed(ssr_dict)
  `
报错内容：

> D:\MyPython\venv\Scripts\python.exe D:/MyProject/MyEcProject/test/test_切换ssr.py
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "D:\MyProject\MyEcProject\test\test_切换ssr.py", line 16, in <module>
>     ShadowsocksrTest.test_shadowsocksr_speed(ssr_dict)
>   File "D:\MyPython\venv\lib\site-packages\shadowsocksr_cli\logger.py", line 51, in main
>     func(*args, **kwargs)
>   File "D:\MyPython\venv\lib\site-packages\shadowsocksr_cli\network_test_utils.py", line 94, in test_shadowsocksr_speed
>     p.start()
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Users\ligen\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> 2021-04-06 17:21:48,831 - network_test_utils.py[line:117] - [test_shadowsocksr_speed] - INFO: Shadowsocksr - name: 入门-香港微软云03-上海中转 - 14436 单端口
> 2021-04-06 17:21:48,831 - network_test_utils.py[line:118] - [test_shadowsocksr_speed] - INFO: Download: ∞ MB/s
> 2021-04-06 17:21:48,831 - network_test_utils.py[line:119] - [test_shadowsocksr_speed] - INFO: Upload: ∞ MB/s
> 2021-04-06 17:21:48,831 - logger.py[line:53] - [main] - INFO: Func - test_shadowsocksr_speed Total time: 2.04s
> 
> Process finished with exit code 0
>

**Comment by ligenxun** [comment]
测试环境：Virtualenv ，Python 3.7

**Comment by TyrantLucifer** [comment]
原因是这样的，测速底层采取多线程，子线程负责启动shadowsocksr代理，主线程负责进行测速工作，在采用多线程开发的时候使用了Process模块，然而该模块因为操作系统底层的缘故在Linux和Windows下实现多线程的方式不同，详情解释可参考网上的一篇博客：`https://blog.csdn.net/qm5132/article/details/82999279`，所以如果在Windows想要运行测速逻辑，需要将代码封装成方法，例如这样：
```python
from shadowsocksr_cli.parse_utils import *
from shadowsocksr_cli.network_test_utils import *

def main():
    ssr_url = "ssr://【ssr链接】"
  
    ssr_dict = ParseShadowsocksr.parse_shadowsocksr(ssr_url)
    ssr_dict = ShadowsocksrTest.test_shadowsocksr_connect(ssr_dict)
    ShadowsocksrTest.test_shadowsocksr_speed(ssr_dict)

if __name__ == "__main__":
    main()
```
![image](https://user-images.githubusercontent.com/51053924/113702092-a397c880-970b-11eb-95b3-3042dd60b3cc.png)

**Comment by ligenxun** [comment]
> 原因是这样的，测速底层采取多线程，子线程负责启动shadowsocksr代理，主线程负责进行测速工作，在采用多线程开发的时候使用了Process模块，然而该模块因为操作系统底层的缘故在Linux和Windows下实现多线程的方式不同，详情解释可参考网上的一篇博客：`https://blog.csdn.net/qm5132/article/details/82999279`，所以如果在Windows想要运行测速逻辑，需要将代码封装成方法，例如这样：
> 
> ```python
> from shadowsocksr_cli.parse_utils import *
> from shadowsocksr_cli.network_test_utils import *
> 
> def main():
>     ssr_url = "ssr://【ssr链接】"
>   
>     ssr_dict = ParseShadowsocksr.parse_shadowsocksr(ssr_url)
>     ssr_dict = ShadowsocksrTest.test_shadowsocksr_connect(ssr_dict)
>     ShadowsocksrTest.test_shadowsocksr_speed(ssr_dict)
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> ![image](https://user-images.githubusercontent.com/51053924/113702092-a397c880-970b-11eb-95b3-3042dd60b3cc.png)

哦哦哦！好的好的，明白了，学到了！
非常感谢大佬的指点！
