### ISSUE TITLE
扶墙的正确姿势是什么

### ISSUE THREAD

**Issue by XueJingLiiu** [TyrantLucifer/ssr-command-client#4]
作者你好，我觉得这个项目很不错，我很想通过它来富强上网，但是在使用过程中遇到了问题，希望你能帮我看看。
我首先设置了订阅链接，并更新了ssr节点，然后开启了ssr代理服务，并设置了本地代理，接下来生成了最快节点的json文件，在查看ip归属地时显示的ip确实也是订阅ssr后的线路。当我觉得已经成功时，满怀信心地访问google，然而依旧不能访问，不知是什么原因，希望能得到你的解答。
![pic1](https://user-images.githubusercontent.com/37094842/76937102-1a122e80-692f-11ea-90e3-5a80a6ab222b.png)
(setproxy和ip命令都已经加入了环境变量中)

**Comment by TyrantLucifer** [comment]
按照您的截图看来，您已经成功设置了代理，直接用wget的话走的是本机的dns，然而国内的dns都会污染墙外地址，所以会发生connect错误的提示，所以您需要使用`curl --proxy socks5h://127.0.0.1:1080 www.google.com` 去实现您的需求，这条命令会让curl走socks5代理且使用代理的dns访问，一般您使用ip发现ip归属地是节点的归属地的话，此刻终端是设置代理成功的，开发这款客户端的初衷是为了加快github访问速度，同时也是方便在Linux环境下使用，本质实际上就是在你Linux客户端开启一个socks5代理，这个代理也可以分享给局域网内其他设备使用，只需要将代理地址从127.0.0.1改成局域网地址即可，而且要将防火墙的1080端口开放，这样其他设备设置socks5代理直接指向Linux设备ip即可，通过代理就可以访问google了，更高级在终端的用法可以搜索一下`proxychains`，可以实现指定某条命令走代理，如果还有问题可以继续提问，感谢使用`ssr-command-client`

**Comment by XueJingLiiu** [comment]
感谢大佬耐心的解答，使用你提供的命令发现确实可以扶墙，又学到了！
我还有一个问题就是可否向线路列表新增单条线路，而不是通过订阅链接的方式一下新增一批线路，因为有的软件只提供了单条线路的ssr链接而没有提供订阅链接，比如poro免费版。

**Comment by TyrantLucifer** [comment]
这个功能在项目开发计划之中，尽请期待，请时刻关注本项目，项目README末尾有我的个人微信公众号，如果觉得本项目有用的话可以扫码关注哟，平时会推送一些好玩的东西~

**Comment by XueJingLiiu** [comment]
感谢作者的无私奉献，我已经关注了你的微信公众号。

**Comment by XueJingLiiu** [comment]
感谢ssr-command-client!
将ssr-command-client与privoxy结合使用，终于实现了科学上网!
![png2](https://user-images.githubusercontent.com/37094842/77028392-92323000-69d3-11ea-8616-eb09995310bd.png)
