### ISSUE TITLE
方便做Mac OS适配吗？

### ISSUE THREAD

**Issue by stevenhobs** [TyrantLucifer/ssr-command-client#43]
发现还是命令行最好用，老哥不做mac适配是因为没机器还是不太好搞。

**Comment by TyrantLucifer** [comment]
没机器呢，我找个机器弄一下哈。

**Comment by stevenhobs** [comment]
可以考虑用个黑苹果机器

**Comment by 2018DHY** [comment]
mac os源生就支持，和Linux差不多，开启shadowsocks后在设置->网络->代理选择socks5，然后填入127.0.0.1:1080然后应用就行了,最好别用默认的端口1080，有时候被占用了，所以网络就不通，可以换成1000什么的

**Comment by TyrantLucifer** [comment]
好像m1芯片多线程那块会有点问题，有没有m1机器测一下呀，intel的没问题肯定能用

**Comment by liuyike98** [comment]
> 好像m1芯片多线程那块会有点问题，有没有m1机器测一下呀，intel的没问题肯定能用

刚把m1的卖了,等明年上个m1 max玩玩哈哈,这个项目看上去很不错

**Comment by TyrantLucifer** [comment]
v2.1.5版本已经做好mac的适配，请升级一下。
