### ISSUE TITLE
怎样移除手动添加的节点

### ISSUE THREAD

**Issue by liuyike98** [TyrantLucifer/ssr-command-client#48]
用--add-ssr SSR_URL 手动添加ss后,找不到怎么移除,是我眼神不好没找到吗?请教一下怎么删掉

**Comment by liuyike98** [comment]
![image](https://user-images.githubusercontent.com/87092276/141517013-f1153049-75f0-4112-85bd-8f86e1081352.png)
可否帮忙看看这是为什么呢?其他软件都可以连接说明ssr是没问题的,我通过这个本地端口取requests就不行,然后发现ss-cli报错如下

**Comment by liuyike98** [comment]
> ![image](https://user-images.githubusercontent.com/87092276/141517013-f1153049-75f0-4112-85bd-8f86e1081352.png) 可否帮忙看看这是为什么呢?其他软件都可以连接说明ssr是没问题的,我通过这个本地端口取requests就不行,然后发现ss-cli报错如下

是不支持这种加密方式吗

**Comment by TyrantLucifer** [comment]
1. 目前没有删除节点的方式，唯一的方式就是更新订阅，此时列表里的所有节点将会你是订阅链接的节点，后续版本可以加上删除节点的功能
2. chacha20-ietf加密方式需要自己在本机安装加密库才能使用
- linux详见https://0b2bd010.wiz06.com/wapp/pages/view/share/s/0baZ0g2Y0h7E2nCs-V3z8FhA0uorhp19pAP92-63v23qMflo，
- windows版本需要下载libsodium dll文件，详见https://download.libsodium.org/libsodium/releases/，然后将文件放置到C:/windows/system32中

**Comment by DavidYordan** [comment]
C:\WINDOWS\system32>shadowsocksr-cli -s 115
2022-06-05 17:11:29,655 - asyncdns.py[line:289] - [__init__] - INFO: black_hostname_list init as : []
2022-06-05 17:11:29,655 - asyncdns.py[line:337] - [_parse_resolv] - INFO: dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]
2022-06-05 17:11:29,655 - handle_utils.py[line:69] - [start_on_windows] - INFO: Shadowsocksr is start on 127.0.0.1:1080
2022-06-05 17:11:29,655 - handle_utils.py[line:70] - [start_on_windows] - INFO: Press Ctrl+C to stop shadowsocksr
2022-06-05 17:11:33,932 - util.py[line:94] - [find_library] - INFO: loading libsodium from C:\WINDOWS\system32\libsodium.dll

文件放进去后变成这个了，然后卡住不动了，仍然无法使用

**Comment by TyrantLucifer** [comment]
本来windows下就是进程在阻塞执行的，自己在浏览器设置socks5代理

> C:\WINDOWS\system32>shadowsocksr-cli -s 115 2022-06-05 17:11:29,655 - asyncdns.py[line:289] - [**init**] - INFO: black_hostname_list init as : [] 2022-06-05 17:11:29,655 - asyncdns.py[line:337] - [_parse_resolv] - INFO: dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)] 2022-06-05 17:11:29,655 - handle_utils.py[line:69] - [start_on_windows] - INFO: Shadowsocksr is start on 127.0.0.1:1080 2022-06-05 17:11:29,655 - handle_utils.py[line:70] - [start_on_windows] - INFO: Press Ctrl+C to stop shadowsocksr 2022-06-05 17:11:33,932 - util.py[line:94] - [find_library] - INFO: loading libsodium from C:\WINDOWS\system32\libsodium.dll
> 
> 文件放进去后变成这个了，然后卡住不动了，仍然无法使用

本来windows下就是进程在阻塞执行的，自己在浏览器设置socks5代理才能用。
