### ISSUE TITLE
安装方式里的脚本写错了

### ISSUE THREAD

**Issue by YQGong** [TyrantLucifer/ssr-command-client#5]
安装方式
git clone https://github.com/TyrantLucifer/ssr-comm**e**nd-client.git
pip3 install -r requirement.txt

**Comment by TyrantLucifer** [comment]
亲，请问您报什么错了呢

**Comment by YQGong** [comment]
command写成了commend，所以报git仓库不存在的错。

**Comment by YQGong** [comment]
另外main.py的第八行也写错了
    parser = argparse.ArgumentParser(description="The ssr commend client based Python.")
应该改为
    parser = argparse.ArgumentParser(description="The ssr command client based Python.")

**Comment by TyrantLucifer** [comment]
好的，感谢您的提醒，马上改正~~~

**Comment by TyrantLucifer** [comment]
请问还有什么错误吗，没有的话我将关闭这个issue
