### ISSUE TITLE
shadowsocksr_cli/main.py中调用UpdateSystemProxy.open_global_proxy报错

### ISSUE THREAD

**Issue by yuzdoge** [TyrantLucifer/ssr-command-client#53]
Ubuntu20.04，
`$shadowsocksr-cli --setting-global-proxy`

`Traceback (most recent call last):
  File "/usr/local/bin/shadowsocksr-cli", line 11, in <module>
    load_entry_point('shadowsocksr-cli==2.1.5', 'console_scripts', 'shadowsocksr-cli')()
  File "/usr/local/lib/python3.8/dist-packages/shadowsocksr_cli-2.1.5-py3.8.egg/shadowsocksr_cli/main.py", line 88, in main
    UpdateSystemProxy.open_global_proxy(args.port, args.http_port)
  File "/usr/local/lib/python3.8/dist-packages/shadowsocksr_cli-2.1.5-py3.8.egg/shadowsocksr_cli/logger.py", line 65, in judge
    func(*args, **kwargs)
TypeError: open_global_proxy() takes 1 positional argument but 2 were given`

shadowsocksr_cli/functions.py中

` 214 @is_ubuntu`
`215 def open_global_proxy(local_port):  `
少了个变量，更改为`def open_global_proxy(local_port, http_port=80):  `运行成功
`shadowsocksr-cli --setting-global-proxy`
`2021-12-15 10:43:54,872 - functions.py[line:222] - [open_global_proxy] - INFO: open global socks5 proxy - 127.0.0.1:1080`

但设置系统代理后，firefox使用系统代理选项依旧无法扶墙，但手动设置通过sock5代理却可以，请问是什么原因呢？

**Comment by TyrantLucifer** [comment]
我看一下哈

**Comment by TyrantLucifer** [comment]
默认命令行会传两个参数进来，我改一下，目前我是Ubuntu20.04，我改正之后这个功能没啥问题

**Comment by TyrantLucifer** [comment]
更新一下

**Comment by yuzdoge** [comment]
ok，更新后正常使用，感谢！！！
