### ISSUE TITLE
删除掉默认的订阅之后添加新的订阅，程序出错。

### ISSUE THREAD

**Issue by YQGong** [TyrantLucifer/ssr-command-client#6]
删除掉默认的订阅之后添加新的订阅后：
.ssr-command-client/config.ini中：
subscribe_url = ,https://xxx

逗号前面的空格导致协议解析错误

**Comment by TyrantLucifer** [comment]
您好，可以使用python3 main.py --setting subscribe_url去重置订阅链接~~~

**Comment by TyrantLucifer** [comment]
除了上方的解决方法，我已经修复bug，现在移除链接为0个之后，再添加新的链接不会再出现有逗号的情况了
