### ISSUE TITLE
可以配置成1端口对应1节点,同时监听多个端口吗?

### ISSUE THREAD

**Issue by xzone911** [TyrantLucifer/ssr-command-client#62]
可以配置成1端口对应一个节点,同时监听多个端口吗?

**Comment by TyrantLucifer** [comment]
Linux下不支持多开，Windows下支持多开

**Comment by PhD-5** [comment]
> Linux下不支持多开，Windows下支持多开

现在是不是都不支持多开了？
1. 根据help信息，执行时无法同时指定多个 -s -p，后面会覆盖前面
2. 多次执行 cli，会提示Error already running
