### ISSUE TITLE
负载均衡

### ISSUE THREAD

**Issue by R3col** [TyrantLucifer/ssr-command-client#64]
大哥能不能加个负载均衡（根据连接情况 自动选择节点），如果这个结构下方便的话，感谢 = =

**Comment by TyrantLucifer** [comment]
目前市面上有很多图形化界面客户端已经满足了这个功能，我就没必要去造这个轮子了，本来这个客户端的使用场景就是给服务器用或者linux下用的，所以负载均衡这个功能需求点已经是桌面级操作系统的了，与其这样还不如用其他图形化界面客户端。

**Comment by R3col** [comment]
我是在服务器上用的，可能场景比较特殊，我找下其他工具吧，感谢大哥回复。
