### ISSUE TITLE
"INFO: Shadowsocksr is started", but lsOF -I :1088 not found

### ISSUE THREAD

**Issue by LongQIByte** [TyrantLucifer/ssr-command-client#66]
"INFO: Shadowsocksr is started", but failed to start.

After modifying the source code to change 'sys.exit()' to 'return', it will not work properly later. Restart, uninstall (PIP uninstall Shadowsocksr -cli) and reinstall (PIP install Shadowsocksr -cli) are still unavailable
Change the source code to sys.exit() and change it to return. Restart, uninstall (PIP uninstall Shadowsocksr -cli) and reinstall (PIP install Shadowsocksr -cli) are still unavailable

```
(base) ➜  SSR shadowsocksr-cli -s 76 -p 1088
2022-04-12 22:10:05,991 - daemon.py[line:124] - [daemon_start] - INFO: Shadowsocksr is started
(base) ➜  SSR lsof -i:1088
(base) ➜  SSR 
```

**Comment by TyrantLucifer** [comment]
Please offer the error log that in `~/.ssr-command-client` and check whether encrypt method of the shadowsocksr node is `chacha20-ietf`, if it, please ensure that `libsodium` library had been installed in your operator system. You can find the detail at the following url: 
https://0b2bd010.wiz06.com/wapp/pages/view/share/s/0baZ0g2Y0h7E2nCs-V3z8FhA0uorhp19pAP92-63v23qMflo

**Comment by TyrantLucifer** [comment]
Is any problems? If not, I will close this issue. Thanks

**Comment by becaHEse** [comment]
ubuntu，python3.10.6，我遇到了相同的问题，使用 curl --proxy socks5h://127.0.0.1:1080 www.google.com出现问题
![image](https://user-images.githubusercontent.com/108858665/222898475-de82527c-035c-4c05-92f6-87595e3d6b59.png)
![image](https://user-images.githubusercontent.com/108858665/222898853-8a3da6de-bc26-438c-be52-adfd6766bb3d.png)


但是在我本地windows没有问题，curl --proxy socks5h://127.0.0.1:1080 www.google.com 也有正常返回
![image](https://user-images.githubusercontent.com/108858665/222898606-0818ba54-3281-4c70-b7c0-d66cc18e4274.png)
![image](https://user-images.githubusercontent.com/108858665/222899037-18da5ddf-a81c-4c28-94fd-f996ae7f80ee.png)

**Comment by becaHEse** [comment]
另外就是，在我的ubuntu上面其他的指令（--parse-url、--test-again等）都没有问题，防火墙1080端口也开启了，加密方式是aes-256-cfb
