### ISSUE TITLE
python main.py --add-ssr   失败

### ISSUE THREAD

**Issue by neosun100** [TyrantLucifer/ssr-command-client#7]
python main.py --add-ssr  该参数调用是什么格式

我三种都测试了，全部返回  please input correct ssr url~~

ssr://MTkyLjE2OC4yNTUuMjE4OjExMTExOmF1dGhfYWVzMTI4X3NoYTE6Y2hhY2hhMjA6dGxzMS4yX3RpY2tldF9hdXRoOlRFOVBVREowYUdWdGIyOXUvP29iZnNwYXJhbT0mcHJvdG9wYXJhbT0mcmVtYXJrcz1aR1Z0YncmZ3JvdXA9VG1Wdg

还是再对其base64后的信息
c3NyOi8vTVRreUxqRTJPQzR5TlRVdU1qRTRPakV4TVRFeE9tRjFkR2hmWVdWek1USTRYM05vWVRFNlkyaGhZMmhoTWpBNmRHeHpNUzR5WDNScFkydGxkRjloZFhSb09sUkZPVkJWUkVvd1lVZFdkR0l5T1hVdlAyOWlabk53WVhKaGJUMG1jSEp2ZEc5d1lYSmhiVDBtY21WdFlYSnJjejFhUjFaMFluY21aM0p2ZFhBOVZHMVdkZwo=

还是 ssr://后的信息
MTkyLjE2OC4yNTUuMjE4OjExMTExOmF1dGhfYWVzMTI4X3NoYTE6Y2hhY2hhMjA6dGxzMS4yX3RpY2tldF9hdXRoOlRFOVBVREowYUdWdGIyOXUvP29iZnNwYXJhbT0mcHJvdG9wYXJhbT0mcmVtYXJrcz1aR1Z0YncmZ3JvdXA9VG1Wdg

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/77731538-0efd8380-703e-11ea-97d2-968a4773af01.png)
如图，我测试没有问题，不知道您的版本是否为最新版本，如果不是，请使用git pull进行更新，谢谢~

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/77732562-102fb000-7040-11ea-976e-e086fe96044f.png)

**Comment by SSShooter** [comment]
这边用了sudo正常，不sudo会提示please input correct ssr url~~

**Comment by TyrantLucifer** [comment]
> 这边用了sudo正常，不sudo会提示please input correct ssr url~~

原因是这样的，在解析出ssr节点信息之后，python会调用ping3模块去测试服务器的ping值，而ping3的使用需要有超级权限，所以需要加sudo，这样在缓存ssr节点信息之后，缓存文件所属主就变成了root，在调用--add-ssr这个命令的同时会更新本地缓存文件，从而导致普通权限无法修改，在develop分支将测试节点ping的方式从ping3改变为fping，fping是第三方工具，需要额外安装，但不需要root权限，所有操作都可以在普通用户下进行，如果觉得用的不是很爽可以切换到develop分支，在切换之后需要删除本地缓存文件：~/.ssr-command-client/ssr-list.json，然后再进行更新。
