### ISSUE TITLE
请问如何开启socks5局域网访问

### ISSUE THREAD

**Issue by saymyname77** [TyrantLucifer/ssr-command-client#72]

**Comment by TyrantLucifer** [comment]
本地监听地址设置成你网卡地址，一个局域网内的就可以连接了

**Comment by saymyname77** [comment]
> 本地监听地址设置成你网卡地址，一个局域网内的就可以连接了

设置为0.0.0.0或本机内网ip都不行

**Comment by BrightXiaoHan** [comment]
请问要如何设置本地监听呢

**Comment by crychicer** [comment]
我看了参数设置代码才发现这个命令行每次只能一个参数，命令正确使用顺序：shadowsocksr-cli --setting-address 0.0.0.0，然后再shadowsocksr-cli -s  id，这样设置才会生效，生效后日志输出的是设置的ip，如果这样还不行可能就是其他问题了

**Comment by RexWzh** [comment]
按这个顺序执行了，局域网 socks5 有效，但是  http 不生效怎么办。
