### ISSUE TITLE
请问怎么怎么使用http代理？

### ISSUE THREAD

**Issue by kennyliu2015** [TyrantLucifer/ssr-command-client#74]
我现在用socks5代理是成功搞定了。
但有些程序要用http代理，
我是用--http start，我以为这样开启，但开启后也没法连通。
如果程序本身可以实现，我就不需要用到 provoxy来转换了。
请教一下。感谢

**Comment by TyrantLucifer** [comment]
#63

**Comment by BrightXiaoHan** [comment]
> 我现在用socks5代理是成功搞定了。 但有些程序要用http代理， 我是用--http start，我以为这样开启，但开启后也没法连通。 如果程序本身可以实现，我就不需要用到 provoxy来转换了。 请教一下。感谢

可以试一下我事先的socks转http的功能 #94
