### ISSUE TITLE
Why did it show that "127.0.0.1:1080" refused to be connected after I export ALL_PROXY=socks5://127.0.0.1:1080

### ISSUE THREAD

**Issue by gaohuiguo88** [TyrantLucifer/ssr-command-client#8]
![image](https://user-images.githubusercontent.com/32334299/80926995-73de9300-8dcd-11ea-9368-6931ec8cb99a.png)
As the image shows the operation I have done, I am still able to visit the website in China but fail to visit some websites like google or youtube. I am confused and hope to find the solution to this problem. Thank you.

**Comment by TyrantLucifer** [comment]
You should use `python3 main.py -S` to stop proxy and use `python3 main.py -s` to restart proxy.
This error seems that proxy is not work successfully

**Comment by gaohuiguo88** [comment]
![image](https://user-images.githubusercontent.com/32334299/81031002-5ab50f80-8ebd-11ea-8171-f7bb4d890f7b.png)
Thanks! Your idea does work!
