### ISSUE TITLE
【wmware ubuntu 20.04】【curl cip.cc 显示代理为美国 但火狐无法连接google】

### ISSUE THREAD

**Issue by zjuadurey** [TyrantLucifer/ssr-command-client#80]
我打开了一个客户端 并使用了 setproxy（设置端口只在这个终端起效），之后是shadowsocksr-cli --start  13 选择了我的美国节点。

为了测试是否可用，我使用了 curl cip.cc，返回值确实显示为美国地址。

但是firefox无法连接上google，下面是一些尝试：

1.可能我的节点不能用？我在实体机windows上测试了该节点可用

2.firefox->setting->network settings  可能要设置 Use system proxy settings，设置后google依旧无法连接

3。firefox可能需要在上述终端中运行？ 我在设置好setproxy后 在同一个终端用命令行打开了firefox，但是google依旧无法连接

请问这应该是什么情况呢？烦请作者解惑这稍加指点。

谢谢！已经star哈

**Comment by TyrantLucifer** [comment]
Download `SwitchyOmega` plugin in your firefox.

**Comment by zjuadurey** [comment]
谢谢！ 确实好用
