### ISSUE TITLE
http代理不能正常访问

### ISSUE THREAD

**Issue by linkaka970105** [TyrantLucifer/ssr-command-client#86]
开启http代理后，linux terminal配置了相应的http代理，通过curl http://www.google.com 测试，返回错误“file not found, 请输入正确的url%”，看了源代码，不太理解def __deal_request函数下f = open(ret[1:], "rb")的打开文件的操作是想做什么，根据请求切分后的路径打开文件，这个文件大概率不存在呀，作为http代理不是帮忙代理转发相应的请求，然后将请求结果返回就好了吗，大佬有空的话帮忙解答下哈

**Comment by oonexdl** [comment]
![image](https://github.com/TyrantLucifer/ssr-command-client/assets/13810673/f95b23df-4e29-4361-82cd-613d3dd740c0)
类似的问题，我这边返回 `HTTP code 404`

**Comment by TyrantLucifer** [comment]
Do not support http proxy. Only socks5 proxy
