### ISSUE TITLE
[经验] 关于在 Ubuntu 22.04 和 OpenSSL 3 下的 RC4-MD5 算法的问题

### ISSUE THREAD

**Issue by vinsonws** [TyrantLucifer/ssr-command-client#90]
### 环境

操作系统：Ubuntu 22.04.1 LTS
OpenSSL：OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

### 发现问题

我的ssr使用的算法是 rc4-md5，而且官方不提供修改，简单尝试 #52  与 python3.8 后发现问题不在这里。
于是运行 [encrypt_test.py](https://github.com/TyrantLucifer/ssr-command-client/blob/master/shadowsocksr_cli/shadowsocks/encrypt_test.py):

```shell
python3 shadowsocksr_cli/shadowsocks/encrypt_test.py
```

发现除了rc4-md5外的算法都是正常的。

### 问题解决

在 openssl 3.x 中 rc4-md5 作为遗留算法是默认关闭的，在[开启Legacy Providers](https://blog.vinsonws.cn/2023/05/25/openssl-openssl3-%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF-rc4-md5-%E6%94%AF%E6%8C%81/)后，再次运行 [encrypt_test.py](https://github.com/TyrantLucifer/ssr-command-client/blob/master/shadowsocksr_cli/shadowsocks/encrypt_test.py):

```bash
rc4_md5
test start
speed: 154421384 bytes/s

aes-256-cfb
test start
speed: 191180969 bytes/s

aes-128-cfb
test start
speed: 216546531 bytes/s

bf-cfb
test start
speed: 48175793 bytes/s

camellia-128-cfb
test start
speed: 73863755 bytes/s

cast5-cfb
test start
speed: 40460525 bytes/s

idea-cfb

seed-cfb
test start
speed: 38325344 bytes/s

salsa20

chacha20
```

启动代理，检查ip，运行结果如下：
![image](https://github.com/TyrantLucifer/ssr-command-client/assets/32018959/59befaf7-b72a-4fbc-8ed3-606aa40fc681)

**Comment by TyrantLucifer** [comment]
牛皮呀哥们！！！一定给你顶一下

**Comment by yuanjinlong** [comment]
解决燃煤之急。非常感谢。我都有想退版本的打算了

**Comment by zhuhaozh** [comment]
补充一点：
如果发现改完还是不行的话，尝试使用`openssl version -d`来确认修改的配置文件在该目录下

Ref: 
https://www.practicalnetworking.net/practical-tls/openssl-3-and-legacy-providers/

**Comment by gaohongy** [comment]
厉害厉害，解决了

**Comment by 110560** [comment]
"method": "none",
            "protocol": "auth_chain_a",
            "protocol_param": "#",
            "obfs": "plain",
            "obfs_param": ""

这个配置咋办有没有大佬知道
Python 3.11.2 OpenSSL 3.0.2下
ShadowsocksR 服务端 没有看到有人在维护了。。 如果有@我一下
