### ISSUE TITLE
开启http后怎么在python中设置代理？

### ISSUE THREAD

**Issue by BigBean666** [TyrantLucifer/ssr-command-client#92]
大佬您好。
我已经起了shadowsockr的服务，并且起了http服务，指定了http-port为1888
请问我如何在python中设置代理呢？
我设置了
proxy = {
'http': 'http://0.0.0.0:1888',
'https': 'http://0.0.0.0:1888'
}
但还是无法访问网站，麻烦您看看

**Comment by BigBean666** [comment]
啊我自己试出来了，希望能帮到同样有需要的人。
这个项目相当于开了sock5，我自己是再使用privoxy吧sock5转为了http代理，然后就可以在代码用调用了

**Comment by BrightXiaoHan** [comment]
请问怎么把socks5代理转成http呢
